In [1]:
import numpy as np
np.__version__

'1.18.1'

In [2]:
np?

In [3]:
np.array(34)

array(34)

In [4]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [7]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [8]:
np.array??

In [9]:
a = np.zeros(10, dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
type(a[1])

numpy.int32

In [11]:
np.empty(3)

array([1.20563906e-311, 0.00000000e+000, 6.47591605e-319])

In [12]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [13]:
print("x3 ndim: ", x3.ndim) #次元
print("x3 shape: ", x3.shape) #各次元のサイズ
print("x3 size: ", x3.size) #配列の合計サイズ

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [14]:
print("dtype: ", x3.dtype)

dtype:  int32


In [15]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")
# 一般的に、nbytesはitemsizeにsizeを乗じた値となる

itemsize:  4 bytes
nbytes:  240 bytes


In [16]:
import sys
print("Python version =",sys.version)
print("Python platform =",sys.platform)
print("Python intger=",sys.int_info)
print("Python float =",sys.float_info)

Python version = 3.8.2 (default, May  6 2020, 09:02:42) [MSC v.1916 64 bit (AMD64)]
Python platform = win32
Python intger= sys.int_info(bits_per_digit=30, sizeof_digit=4)
Python float = sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)


In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
x1[0]

5

In [19]:
x1[4]

7

In [20]:
x1[-1]

9

In [21]:
x1[:1]

array([5])

In [22]:
x1[1:]

array([0, 3, 3, 7, 9])

In [23]:
type(x1[0])

numpy.int32

In [24]:
x1[0] = 3.14159265
x1

array([3, 0, 3, 3, 7, 9])

In [25]:
type(x1[0])

numpy.int32

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[0]=12
x2

array([[12, 12, 12, 12],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
np.random.seed(0)
x2 = np.random.randint(10, size=(3, 4))
x2[0,0]=12
x2

array([[12,  0,  3,  3],
       [ 7,  9,  3,  5],
       [ 2,  4,  7,  6]])

In [29]:
print(type(print(x2[:, 0])))

[12  7  2]
<class 'NoneType'>


In [30]:
print(x2[0])

[12  0  3  3]


In [31]:
# Python list
p_list = [1, 2, 3, 4]
p_list

[1, 2, 3, 4]

In [32]:
p_list_12 = p_list[:2]
p_list_12

[1, 2]

In [33]:
p_list_12[0] = 5
p_list_12

[5, 2]

In [34]:
p_list

[1, 2, 3, 4]

In [35]:
print(x2)

[[12  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [36]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  0]
 [ 7  9]]


In [37]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 7  9]]


In [38]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [39]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [ 7  9]]


In [40]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  0]
 [ 7  9]]


In [41]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [42]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
x=np.array([1,2,3])

# row vector via reshape
print(x.reshape((1, 3)))
print(x.reshape((3, 1)))

[[1 2 3]]
[[1]
 [2]
 [3]]


In [44]:
# row vector via newaxis
print(x[np.newaxis, :])
print(x[:, np.newaxis])


[[1 2 3]]
[[1]
 [2]
 [3]]


In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [46]:
z = [99, 99, 99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [47]:
grid = np.array([[1, 2, 3],
                        [4, 5, 6]])

In [48]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                        [6, 4, 4]])

np.vstack([x, grid])
# np.vstack([grid, x])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 4, 4]])

In [51]:
y = np.array([[99],
                    [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  4,  4, 99]])

In [52]:
grid1 = np.array([[9, 8, 7],
                        [6, 4, 4]])
grid2 = np.array([[1, 2, 3],
                        [4, 5, 6]])
np.dstack([grid1, grid2])

array([[[9, 1],
        [8, 2],
        [7, 3]],

       [[6, 4],
        [4, 5],
        [4, 6]]])

In [53]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [54]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.5 s ± 618 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [56]:
%timeit (1.0 / big_array)

12.7 ms ± 3.24 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [57]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [58]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [59]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [60]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [61]:
np.add(x, 2)

array([2, 3, 4, 5])

In [62]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [63]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [64]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [65]:
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
abs(x)

array([5., 5., 2., 1.])

In [66]:
theta = np.linspace(0, np.pi, 3) #np.pi = π

In [67]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [68]:
x = [-1, 0, 1]
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [69]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [70]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [71]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [72]:
from scipy import special

In [73]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [74]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [75]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [77]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [78]:
np.multiply.reduce(x)

120

In [79]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [80]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [81]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])